apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-ui
  template:
    metadata:
      labels:
        app: library-ui
    spec:
      containers:
      - name: ui
        image: library-ui
        imagePullPolicy: Never
        ports:
        - containerPort: 80